---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: 'Avant de déployer les outils ONTAP pour VMware vSphere, vous devez connaître l"espace requis pour le package de déploiement ainsi que certaines exigences de base en matière de système hôte.' 
---
= Conditions préalables au déploiement des outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de déployer les outils ONTAP pour VMware vSphere, vous devez connaître l'espace requis pour le package de déploiement ainsi que certaines exigences de base en matière de système hôte.

Vous pouvez utiliser les outils ONTAP pour VMware vSphere avec VMware vCenter Server Virtual Appliance (vCSA). Vous devez déployer les outils ONTAP pour VMware vSphere sur un client vSphere pris en charge qui inclut le système ESXi.



== Configuration minimale requise

* *Espace requis pour le package d'installation par nœud*
+
** 10 Go pour les installations à provisionnement fin
** 248 Go pour les installations à provisionnement lourd


* *Exigences de dimensionnement du système hôte par nœud* la mémoire recommandée selon la taille du déploiement et par nœud est indiquée dans le tableau ci-dessous :


|===


| *Type de déploiement* | *CPU* | *Mémoire (Go)* 


| Petit (S) | 8 | 16 


| Moyen (M) | 12 | 24 


| Grand (L) | 16 | 32 
|===
Pour plus d'informations, reportez-vous à la section _limites de configuration pour déployer les outils ONTAP pour VMware vSphere_ ci-dessous.



== Exigences minimales en matière de stockage et d'applications

|===
| Stockage, hôte et applications | Configuration minimale requise pour la version 


| ONTAP | Dernière version de correctif de ONTAP 9.12.1, 9.13.1, 9.14.1 et 9.15.1. 


| Hôtes ESXi | ESXi 7.0.3 


| Serveur vCenter | VCenter 7.0U3 


| Fournisseur VASA | 3,0 


| Application OVA | 10,2 
|===
La matrice d'interopérabilité (IMT) contient les dernières informations sur les versions prises en charge de ONTAP, de vCenter Server, d'hôtes ESXi et d'applications de plug-in.

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Matrice d'interopérabilité"^]



== Limites de configuration pour le déploiement des outils ONTAP pour VMware vSphere

Vous pouvez utiliser le tableau suivant comme guide pour configurer les outils ONTAP pour VMware vSphere.

|===


| *Déploiement* | *Type* | *Nombre de vVols* | *Nombre d'hôtes* | *Type de protocole* 


| Déploiement facile | Petit (S) | ~12 KO | 32 | NFS et iSCSI 


| Déploiement facile | Moyen (M) | ~24 KO | 64 | NFS et iSCSI 


| Haute-disponibilité | Petit (S) | ~24 KO | 64 | NFS et iSCSI 


| Haute-disponibilité | Moyen (M) | environ 50 000 | 128 | NFS et iSCSI 


| Haute-disponibilité | Grand (L) | environ 100 000 | 256 [REMARQUE] le nombre d'hôtes dans le tableau indique le nombre total d'hôtes provenant de plusieurs vCenters. | NFS et iSCSI 
|===
Pour plus de détails sur les exigences de dimensionnement du système hôte par nœud, reportez-vous à link:../deploy/prerequisites.html["Conditions préalables au déploiement des outils ONTAP pour VMware vSphere"]la section .



== Outils ONTAP pour VMware vSphere - Storage Replication adapter (SRA)

Le tableau suivant indique les chiffres pris en charge par instance VMware Live site Recovery à l'aide des outils ONTAP pour VMware vSphere.

|===
| *Taille du déploiement vCenter* | *Petit* | *Moyen* 


| Nombre total de machines virtuelles configurées pour la protection à l'aide de la réplication basée sur les baies | 2000 | 5000 


| Nombre total de groupes de protection de réplication basés sur les baies | 250 | 250 


| Nombre total de groupes de protection par plan de reprise d'activité | 50 | 50 


| Nombre de datastores répliqués | 255 | 255 


| Nombre de VM | 4000 | 7000 
|===
Le tableau suivant indique le nombre de VMware Live site Recovery et les outils ONTAP correspondants pour la taille du déploiement de VMware vSphere.

|===


| *Nombre d'instances de VMware Live site Recovery* | *Déploiement des outils ONTAP taille* 


| Jusqu'à 4 | Petit 


| 4 à 8 | Moyen 


| Plus de 8 | Grand 
|===
Pour plus d'informations, reportez-vous https://docs.vmware.com/en/VMware-Live-Recovery/services/vmware-live-site-recovery/GUID-3AD7D565-8A27-450C-8493-7B53F995BB14.html["Limites opérationnelles de la restauration VMware Live site"]à .



== Contrôles préalables au déploiement

Assurez-vous que les éléments suivants sont en place avant de poursuivre le déploiement :

* L'environnement vCenter Server est configuré et configuré.
* (Facultatif) pour l'utilisateur d'automatisation - le fichier JSON de collections Postman fourni par NetApp est collecté.
* Les informations d'identification du serveur vCenter parent pour déployer l'OVA sont en place.
+

NOTE: Le mot de passe du serveur vCenter parent ne doit pas contenir ces caractères spéciaux ($, ', ").

* Vous disposez des informations de connexion de votre instance de serveur vCenter à laquelle les outils ONTAP pour VMware vSphere se connecteront au post-déploiement, pour inscription.
* Le cache du navigateur est supprimé.
* Assurez-vous que vous disposez de trois adresses IP disponibles pour un déploiement non HA : une adresse IP libre pour l'équilibreur de charge, une adresse IP libre pour le plan de contrôle Kubernetes et une adresse IP pour le nœud. Pour un déploiement haute disponibilité, en plus de ces trois adresses IP, vous aurez besoin de deux adresses IP supplémentaires pour les deuxième et troisième nœuds. Les noms d'hôte doivent être mappés sur les adresses IP libres du DNS avant d'attribuer des déploiements HA et non HA. Les cinq adresses IP du déploiement HA et les trois adresses IP du déploiement non HA doivent se trouver sur le même VLAN que celui sélectionné pour le déploiement.


* Assurez-vous que le nom de domaine sur lequel le certificat est émis est mappé à l'adresse IP virtuelle dans un déploiement multi-vCenter où les certificats d'autorité de certification personnalisée sont obligatoires. _Nslookup_ vérifiez le nom de domaine pour vérifier si le domaine est résolu à l'adresse IP prévue. Les certificats doivent être créés avec le nom de domaine et l'adresse IP de l'adresse IP de l'équilibreur de charge.
* Avant d'installer les outils ONTAP pour VMware vSphere 10.2 dans une configuration avancée non HA et haute disponibilité, consultez l'article de la base de connaissances : https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/pre-requisites_for_installing_OTV_10.1_and_10.2_in_NonHA_Advanced_and_HA["Conditions requises pour la configuration avancée non HA et la configuration haute disponibilité"]

