---
permalink: protect/map-folder.html 
sidebar: sidebar 
keywords:  
summary: Vous devez mapper vos dossiers sur le site protégé et le site de reprise pour permettre la communication entre eux. 
---
= Configurer les mappages de dossiers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez mapper vos dossiers sur le site protégé et le site de reprise pour permettre la communication entre eux.

*Ce dont vous aurez besoin*

Vous devez avoir connecté les sites protégés et de reprise.

*Étapes*

. Connectez-vous à vCenter Server et cliquez sur *site Recovery* > *sites*.
. Sélectionnez votre site protégé et cliquez sur *gérer*.
. Dans l'onglet gérer, sélectionnez *mappages de dossiers*.
. Sélectionnez l'icône *Folder* pour créer un mappage de dossiers.
+
L'assistant de création de mappage de dossier s'affiche.

. Dans l'assistant Créer un mappage de dossier, effectuez les opérations suivantes :
+
.. Sélectionnez *préparer automatiquement les mappages pour les dossiers avec des noms correspondants* et cliquez sur *Suivant*.
.. Sélectionnez les objets de centre de données requis pour les sites protégés et de récupération, puis cliquez sur *Ajouter des mappages*.
.. Cliquez sur *Suivant* une fois les mappages créés.
.. Sélectionnez l'objet utilisé précédemment pour créer le mappage inverse, puis cliquez sur *Terminer*.




*Résultat*

La page mappages des dossiers affiche les ressources du site protégé et les ressources du site de reprise. Vous pouvez suivre les mêmes étapes pour les autres réseaux de votre environnement.
