---
permalink: protect/pair-protected-and-recovery-sites.html 
sidebar: sidebar 
keywords:  
summary: 'Vous devez coupler les sites protégés et de reprise créés à l"aide de votre client vSphere pour permettre à Storage Replication adapter \(SRA\) de détecter les systèmes de stockage.' 
---
= Protection par paires et sites de reprise après incident
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez coupler les sites protégés et de reprise créés à l'aide de votre client vSphere pour permettre à Storage Replication adapter (SRA) de détecter les systèmes de stockage.


NOTE: Storage Replication adapter (SRA) ne prend pas en charge les configurations SnapMirror « Fan-Out ». Les configurations « fan-out » SnapMirror sont celles où un volume source est répliqué vers deux destinations différentes. Cela crée un problème lors de la restauration lorsque VMware Live site Recovery doit restaurer la machine virtuelle à partir de sa destination.

*Ce dont vous aurez besoin*

* VMware Live site Recovery doit être installé sur les sites protégés et de reprise.
* SRA doit être installée sur les sites protégés et de reprise.


*Étapes*

. Double-cliquez sur *site Recovery* sur la page d'accueil du client vSphere et cliquez sur *sites*.
. Cliquez sur *objets* > *actions* > *paire de sites*.
. Dans la boîte de dialogue *pair site Recovery Manager Servers*, entrez l'adresse du contrôleur des services de plate-forme du site protégé, puis cliquez sur *Suivant*.
. Dans la section Select vCenter Server, procédez comme suit :
+
.. Vérifiez que le serveur vCenter du site protégé apparaît comme candidat correspondant au couplage.
.. Entrez les informations d'identification administrateur SSO, puis cliquez sur *Terminer*.


. Si vous y êtes invité, cliquez sur *Oui* pour accepter les certificats de sécurité.


*Résultat*

Les sites protégés et de restauration s'affichent dans la boîte de dialogue objets.
