---
permalink: concepts/ontap-roles.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez définir plusieurs rôles ONTAP recommandés pour l"utilisation des outils ONTAP pour VMware vSphere et le contrôle d"accès basé sur des rôles \(RBAC\). Ces rôles contiennent les privilèges ONTAP requis pour effectuer les opérations de stockage requises qui sont exécutées par les outils ONTAP pour les tâches VMware vSphere.' 
---
= Rôles ONTAP recommandés pour les outils ONTAP pour VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez définir plusieurs rôles ONTAP recommandés pour l'utilisation des outils ONTAP pour VMware vSphere et le contrôle d'accès basé sur des rôles (RBAC). Ces rôles contiennent les privilèges ONTAP requis pour effectuer les opérations de stockage exécutées par les outils ONTAP pour les tâches VMware vSphere.

Pour créer de nouveaux rôles utilisateur, vous devez vous connecter en tant qu'administrateur des systèmes de stockage exécutant ONTAP. Vous pouvez créer des rôles ONTAP à l'aide de ONTAP System Manager 9.8P1 ou version ultérieure.

Chaque rôle ONTAP est associé à une paire nom d'utilisateur et mot de passe, qui constituent les informations d'identification du rôle. Si vous ne vous connectez pas à l'aide de ces informations d'identification, vous ne pouvez pas accéder aux opérations de stockage associées au rôle.

Par mesure de sécurité, les outils ONTAP pour les rôles ONTAP spécifiques à VMware vSphere sont classés de manière hiérarchique. Cela signifie que le premier rôle est le plus restrictif et ne dispose que des privilèges associés à l'ensemble d'outils ONTAP le plus basique pour les opérations de stockage VMware vSphere. Le rôle suivant comprend ses propres privilèges et tous les privilèges associés au rôle précédent. Chaque rôle supplémentaire est moins restrictif quant aux opérations de stockage prises en charge.

Voici quelques-uns des rôles ONTAP RBAC recommandés lors de l'utilisation des outils ONTAP pour VMware vSphere. Après avoir créé ces rôles, vous pouvez les attribuer à des utilisateurs qui doivent effectuer des tâches liées au stockage, telles que le provisionnement de machines virtuelles.

|===


| *Rôle* | *privilèges* 


| Détection | Il permet donc d'ajouter des systèmes de stockage. 


| Créer un stockage | Grâce à ce rôle, vous pouvez créer du stockage. Ce rôle inclut également tous les privilèges associés au rôle découverte. 


| Modifier le stockage | Ce rôle vous permet de modifier le stockage. Ce rôle inclut également tous les privilèges associés au rôle découverte et au rôle Créer un stockage. 


| Détruire le stockage | Vous pouvez ainsi détruire le stockage. Ce rôle inclut également tous les privilèges associés au rôle découverte, au rôle Créer un stockage et au rôle Modifier le stockage. 
|===
Si vous utilisez les outils ONTAP pour VMware vSphere, vous devez également configurer un rôle de gestion basée sur des règles (PBM). Il permet de gérer le stockage à l'aide de règles de stockage. Ce rôle requiert également que vous ayez défini le rôle « questions à poser ».
