---
permalink: configure/associate-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 'besoin d"informations.' 
---
= Associer un back-end de stockage à une instance vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La page de liste vCenter Server affiche le nombre de systèmes back-end de stockage associés. Chaque instance de vCenter Server peut associer un système back-end de stockage.

*À propos de cette tâche*

Cette tâche vous aide à créer un mappage global entre le système back-end de stockage et l'instance vCenter Server intégrée.

*Étapes*

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://loadBalanceIP:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Sélectionnez vCenter dans la barre latérale.
. Cliquez sur les points de suspension verticaux en regard du vCenter que vous souhaitez associer aux systèmes back-end de stockage.
. Sélectionnez Storage backend dans la liste déroulante.
. Sélectionnez l'option *associer le stockage interne* pour associer l'instance vCenter Server au système back-end de stockage requis.

