---
permalink: manage/reset-app-password.html 
sidebar: sidebar 
keywords:  
summary: 'Le mot de passe de l"utilisateur de l"application est utilisé pour l"enregistrement du fournisseur SRA et VASA avec vCenter Server.' 
---
= Réinitialiser le mot de passe utilisateur de l'application
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le mot de passe de l'utilisateur de l'application est utilisé pour l'enregistrement du fournisseur SRA et VASA avec vCenter Server.

*Étapes*

. Lancez le Gestionnaire d'outils ONTAP à partir d'un navigateur Web : `\https://loadBalanceIP:8443/virtualization/ui/`
. Connectez-vous à l'aide des outils ONTAP pour les informations d'identification d'administrateur VMware vSphere que vous avez fournies lors du déploiement.
. Cliquez sur *Paramètres* dans la barre latérale.
. Dans l'écran *informations d'identification de l'utilisateur de l'application*, sélectionnez *Réinitialiser le mot de passe*.
. Indiquez le nom d'utilisateur, le nouveau mot de passe et confirmez les entrées du nouveau mot de passe.
. Cliquez sur *Réinitialiser* pour appliquer les modifications.

